name: Auto Update Hyrox Calendar

on:
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 12:00 UTC
  workflow_dispatch:  # Allows manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Create credentials.json
        run: |
          echo "$CREDENTIALS_JSON" | base64 --decode > credentials.json
          cat credentials.json  # Debugging: Show the file content
        shell: bash
        env:
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}

      - name: Verify credentials.json
        run: cat credentials.json | jq '.'  # Validate JSON format

      - name: Verify RapidAPI Key
        run: |
          if [ -z "$RAPIDAPI_KEY" ]; then
            echo "❌ RAPIDAPI_KEY is missing! Set it in GitHub Secrets."
            exit 1
          else
            echo "✅ RAPIDAPI_KEY found."
          fi
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}

      - name: Run Python Script
        run: python main.py
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
