name: Auto Update Hyrox Calendar

on:
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 12:00 UTC
  workflow_dispatch:  # Allows manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Debug Secrets
        run: echo "Checking if secret exists"; test -n "$CREDENTIALS_JSON" && echo "Secret is present" || echo "Secret is missing"
        shell: bash
        env:
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}

      - name: Create credentials.json
        run: echo "$CREDENTIALS_JSON" > credentials.json
        shell: bash
        env:
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}

      - name: Verify credentials.json
        run: cat credentials.json  # This prints part of the file for debugging (remove later)

      - name: Run Python Script
        run: python main.py
